# Generated by Django 2.1.4 on 2018-12-13 08:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='subscribe_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date subscribed'),
            preserve_default=False,
        ),
    ]
