# Generated by Django 2.1.4 on 2018-12-13 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0003_auto_20181213_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribers',
            name='subscribe_date',
        ),
    ]
