# Generated by Django 2.1.4 on 2018-12-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0004_remove_subscribers_subscribe_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='subscribe_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
