# Generated by Django 2.1.4 on 2018-12-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0005_subscribers_subscribe_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='subscribe_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
