apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddash
  labels:
    app: ddash
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ddash
  template:
    metadata:
      name: ddash
      labels:
        app: ddash
    spec:
      containers:
        - image: "${env.DOCKER_REGISTRY}/${env.JOB_NAME}:${env.BUILD_NUMBER}"
          name: ddash
          ports:
            - containerPort: 80
              protocol: TCP
